dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=mister
matrix:
  fast_finish: true
  allow_failures:
    rust: nightly
  include:
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-musl
  #- env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  #- env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
  - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
  - env: TARGET=aarch64-unknown-linux-gnu
  - env: TARGET=armv7-unknown-linux-gnueabihf
  - env: TARGET=mips-unknown-linux-gnu
  - env: TARGET=mips64-unknown-linux-gnuabi64
  - env: TARGET=mipsel-unknown-linux-gnu
  - env: TARGET=powerpc64-unknown-linux-gnu
  - env: TARGET=powerpc64le-unknown-linux-gnu
  - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  #- env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
before_install: set -e
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: XOgVrDWXnbb5ulJjrqGP8Jns396oqVAT4dz1o9qTuWvMtKgo7JGLA69h9cXFxmiCRwBs2eAQEeWgw2VMrYeXnBZJuKm6+Z8tIC367MrYjL6/GHbsRX48WC/VYVfB4D6Go+8H/9APgAPk7f1nkpWEEMdxzu8QXYeAF3g5wY4u8DF/ULYLg3ukPc2kgoGmoxBrUVwOTJPp03l+MqlNVt/Exglr6s7kspSzrEQ/dWvnc3pLSpPGmMqkY9TWQZKYj19vG5IXRus/zWg4fyXLxafBAIu2Z3fMneZE8x1MsU6SA0hSv6fnUWrRVu5fkJpjXuYBXH7iyFhZfq4XKgSW66emPeX7h1VM+XqHAkRWF8AkVZR2Qy3ElkXtW2Qtf/PNVudMJFV+JCN0Ow+Pj8xXYdjQY4J6xlGFKM1oUCF7cPEKptdLVgK3Iu5Ptm2OyGzkIbUK4DePdQwDZHqA9K95W5upW66CyQgnSUQJBGHAr38Nmj/r9QVZjP3Tchc3Gayo/4FMggydVQMj+u0D7c/HCbR5nZmi+XjPtkpKfx3xl6zGWWB0r0uDX1GodEGriLpUANJ/G5ZfBq4V78EstHuKpFR353zuk+QVL7bdWE+Jc83AtVjZL//MVxwFXYMlW49pjI11kdWVXajUvrhh6HZZVq//bRgTUasFrv8iPneXT/h0m7w=
  file:
    - $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    repo: Jengamon/Mister
    tags: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
  - staging
  - trying
  - dev
notifications:
  email:
    on_success: never
