[package]
name = "mister-gui"
version = "0.1.0"
authors = ["Bob Hostern <bob.hostern@gmail.com>"]

[dependencies]
gfx_core = "^0.6"
nalgebra = "^0.10"
cassowary = "^0.2"
mopa = "^0.2"
palette = "^0.2"
