[package]
name = "mister-gui"
version = "0.1.0"
authors = ["Bob Hostern <bob.hostern@gmail.com>"]

[dependencies]
palette = "^0.2"
cassowary = "^0.2"
nalgebra = "^0.11"
gfx = "^0.14"
petgraph = "^0.4" # when adding nodes / check that new node doesn't cycle
